spring:
  application:
    name: pokemon-design-system
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: pokemon
    password: pokemon
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      show-sql: false
    open-in-view: false