Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 512
      Handler: helloworld.App
      CodeUri: C:\Users\Evandro\Desktop\pokemon-system-design\computer-api\HelloWorldFunction
      Runtime: java21
      Architectures:
        - x86_64